// This is an autogenerated C header file for project 'Expressions'

#ifndef _EXPRESSIONS_H_
#define _EXPRESSIONS_H_

#include <cxcore.h>

//
// Forward type declarations
//

struct CX_ID_2(Expressions, ExpressionExamples);

//
// Type declarations
//

CX_TYPE_DEF(CX_ID_2(Expressions, ExpressionExamples)) {
    struct CX_ID_3(cxcore, System, Object) __base;
};

//
// Function and property declarations
//

extern CX_EXPORT cx_int CX_ID_3(Expressions, ExpressionExamples, Calculate)(cx_int left,
                                                                            cx_int right);
extern CX_EXPORT struct CX_ID_3(cxcore, System, String) *
    CX_ID_3(Expressions, ExpressionExamples,
            DisplayName)(struct CX_ID_3(cxcore, System, String) * preferredName,
                         struct CX_ID_3(cxcore, System, String) * fallbackName);

#endif // _EXPRESSIONS_H_
