// This is an autogenerated C header file for project 'HelloWorld'

#ifndef _HELLOWORLD_H_
#define _HELLOWORLD_H_

#include <cxcore.h>

//
// Forward type declarations
//


//
// Type declarations
//


//
// Function and property declarations
//

extern CX_EXPORT void CX_ID_2(HelloWorld, Main)();


#endif // _HELLOWORLD_H_
