// This is an autogenerated C source file for project 'HelloWorld'

#include "HelloWorld.h"

//
// Strings
//

CX_STRING_DEF(CX_ID_2(HelloWorld, __string_9E77BDB7B7B67BEE), "Hello world!");

//
// Static fields
//

//
// Interface dispatch thunks
//

//
// TypeInfos
//

//
// Functions
//

void CX_ID_2(HelloWorld, Main)() {
    CX_ID_4(cxcore, System, Console, WriteLine)(&CX_ID_2(HelloWorld, __string_9E77BDB7B7B67BEE));
}
