// This is an autogenerated C source file for project 'ArraysAndLoops'

#include "ArraysAndLoops.h"

//
// Strings
//

//
// Static fields
//

//
// Interface dispatch thunks
//

//
// TypeInfos
//

//
// Functions
//

cx_int CX_ID_2(ArraysAndLoops, SumSmallSquares)() {
    struct CX_ID_3(cxcore, System, Array) *squares =
        cx_array_new((cx_uint)(5), (cx_uint)sizeof(cx_int));
    for (cx_int index = 0; (index < 5); (index++)) {
        (*(cx_int *)cx_array_at(squares, (cx_uint)(index), (cx_uint)sizeof(cx_int))) =
            (index * index);
    }
    cx_int total = 0;
    {
        struct CX_ID_3(cxcore, System, Array) *__cx_foreach_collection_square = squares;
        for (cx_uint __cx_foreach_index_square = 0;
             __cx_foreach_index_square < __cx_foreach_collection_square->_length;
             __cx_foreach_index_square++) {
            cx_int square =
                ((cx_int *)__cx_foreach_collection_square->_data)[__cx_foreach_index_square];
            if ((square > 9)) {
                break;
            }
            total += square;
        }
    }
    return total;
}
