// This is an autogenerated C header file for project 'ArraysAndLoops'

#ifndef _ARRAYSANDLOOPS_H_
#define _ARRAYSANDLOOPS_H_

#include <cxcore.h>

//
// Forward type declarations
//


//
// Type declarations
//


//
// Function and property declarations
//

extern CX_EXPORT cx_int CX_ID_2(ArraysAndLoops, SumSmallSquares)();


#endif // _ARRAYSANDLOOPS_H_
