// This is an autogenerated C source file for project 'Properties'

#include "Properties.h"

//
// Strings
//

CX_STRING_DEF(CX_ID_2(__name, ApplicationSettings), "ApplicationSettings");
CX_STRING_DEF(CX_ID_2(__name, Counter), "Counter");
CX_STRING_DEF(__namespace, "");

//
// Static fields
//

//
// Interface dispatch thunks
//

//
// TypeInfos
//

CX_STATIC_CLASS_TYPEINFO_DEF(CX_ID_2(Properties, ApplicationSettings),
                             CX_ID_2(__name, ApplicationSettings), __namespace, 0xB724D7FE1E4772E1,
                             CX_REFLECTION_FLAG_STATIC | CX_REFLECTION_FLAG_VISIBILITY_PUBLIC |
                                 CX_REFLECTION_FLAG_TYPE_CLASS);

CX_BEGIN_VTABLE_DEF(CX_ID_2(Properties, Counter))
CX_END_VTABLE_DEF;
CX_CLASS_TYPEINFO_DEF(CX_ID_2(Properties, Counter), CX_ID_2(__name, Counter), __namespace,
                      CX_ID_4(cxcore, System, Object, __typeinfo), 0xF68BDF28EA03C2B,
                      CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_CLASS);

//
// Functions
//
