// This is an autogenerated C header file for project 'EnumsAndSwitch'

#ifndef _ENUMSANDSWITCH_H_
#define _ENUMSANDSWITCH_H_

#include <cxcore.h>

//
// Forward type declarations
//

typedef enum CX_ID_2(EnumsAndSwitch, TrafficLight) {
    CX_ID_3(EnumsAndSwitch, TrafficLight, Red) = 1,
    CX_ID_3(EnumsAndSwitch, TrafficLight, Yellow) = 2,
    CX_ID_3(EnumsAndSwitch, TrafficLight, Green) = 3
} CX_ID_2(EnumsAndSwitch, TrafficLight);
struct CX_ID_2(EnumsAndSwitch, Signal);

//
// Type declarations
//

CX_TYPE_DEF(CX_ID_2(EnumsAndSwitch, Signal)) {
    struct CX_ID_3(cxcore, System, Object) __base;
};

//
// Function and property declarations
//

extern CX_EXPORT struct CX_ID_3(cxcore, System, String) *
    CX_ID_3(EnumsAndSwitch, Signal, Describe)(CX_ID_2(EnumsAndSwitch, TrafficLight) light);

#endif // _ENUMSANDSWITCH_H_
