// This is an autogenerated C source file for project 'EnumsAndSwitch'

#include "EnumsAndSwitch.h"

//
// Strings
//

CX_STRING_DEF(CX_ID_2(__name, Signal), "Signal");
CX_STRING_DEF(__namespace, "");
CX_STRING_DEF(CX_ID_2(EnumsAndSwitch, __string_6F2BE2FE58CA2BA4), "stop");
CX_STRING_DEF(CX_ID_2(EnumsAndSwitch, __string_BC8DB7393A3D48AB), "slow down");
CX_STRING_DEF(CX_ID_2(EnumsAndSwitch, __string_CDBCA2A1E5E496BB), "go");
CX_STRING_DEF(CX_ID_2(EnumsAndSwitch, __string_EB8BF0D80DB32399), "unknown");

//
// Static fields
//


//
// Interface dispatch thunks
//



//
// TypeInfos
//


CX_BEGIN_VTABLE_DEF(CX_ID_2(EnumsAndSwitch, Signal))
CX_END_VTABLE_DEF;
CX_CLASS_TYPEINFO_DEF(CX_ID_2(EnumsAndSwitch, Signal), CX_ID_2(__name, Signal), __namespace, CX_ID_4(cxcore, System, Object, __typeinfo), 0xD0E0444AB305B7DD, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_CLASS);

//
// Functions
//

struct CX_ID_3(cxcore, System, String)* CX_ID_3(EnumsAndSwitch, Signal, Describe)(CX_ID_2(EnumsAndSwitch, TrafficLight) light) {
    switch (light)
    {
        case CX_ID_3(EnumsAndSwitch, TrafficLight, Red):
        {
            return &CX_ID_2(EnumsAndSwitch, __string_6F2BE2FE58CA2BA4);
        }
        case CX_ID_3(EnumsAndSwitch, TrafficLight, Yellow):
        {
            return &CX_ID_2(EnumsAndSwitch, __string_BC8DB7393A3D48AB);
        }
        case CX_ID_3(EnumsAndSwitch, TrafficLight, Green):
        {
            return &CX_ID_2(EnumsAndSwitch, __string_CDBCA2A1E5E496BB);
        }
        default:
        {
            return &CX_ID_2(EnumsAndSwitch, __string_EB8BF0D80DB32399);
        }
    }
}

